### ISSUE TITLE
Gradient are all NAN when I run GAT/GIN.

### ISSUE THREAD

**Issue by Billy1900** [wujcan/GIF-torch#1]
When I run `python3 main.py --dataset_name cora --target_model GAT --is_train_target_model True --exp Unlearn --method GIF --is_use_node_feature True --num_runs 5 --unlearn_task edge --unlearn_ratio 0.05 --iteration 100 --scale 500`, the `h_estimate` will become NAN after several unlearn iterations. 

`python3 main.py --dataset_name cora --target_model GIN --is_train_target_model True --exp Unlearn --method GIF --is_use_node_feature True --num_runs 5 --unlearn_task edge --unlearn_ratio 0.05 --iteration 100 --scale 500` meets the same issue. Do you know why? @wujcan

**Comment by wujcan** [comment]
We find a large value of 'scale' coefficient can avoid this issue, for example, 10^6 on GIN and 10^5 on GAT.
